In [1]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
l1 = [2, 3, 54, 7]

In [7]:
arr1 = np.array(l1)

In [6]:
l2 = [2, 3, 54.43, 7.12]
np.array(l2)

array([ 2.  ,  3.  , 54.43,  7.12])

In [8]:
type(arr1)

numpy.ndarray

In [16]:
np.arange(10.5, 20.5, 1.5)

array([10.5, 12. , 13.5, 15. , 16.5, 18. , 19.5])

In [2]:
np.arange(10.5, 20.5, 1.5)

array([10.5, 12. , 13.5, 15. , 16.5, 18. , 19.5])

In [3]:
np.arange(10.5, 20.5, 1.5, dtype='int')

array([10, 12, 14, 16, 18, 20, 22])

In [18]:
arr1.size

4

In [19]:
arr1.shape

(4,)

In [20]:
arr1.ndim

1

In [21]:
arr1.dtype

dtype('int32')

## 2D Arrays

In [26]:
arr2 = np.arange(1, 10).reshape( (3, 3, 3) )

In [27]:
arr2.shape

(3, 3)

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2.ndim

2

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr2.size

9

In [2]:
arr3 = np.arange(1, 21).reshape( (4, 5) )

In [41]:
arr3.shape

(4, 5)

In [43]:
np.zeros( (4, 4), dtype='int' )

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
np.ones( (3, 4), dtype= complex )

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [48]:
np.arange(1, 20, 5)

array([ 1,  6, 11, 16])

In [49]:
np.linspace(10, 25, 20)

array([10.        , 10.78947368, 11.57894737, 12.36842105, 13.15789474,
       13.94736842, 14.73684211, 15.52631579, 16.31578947, 17.10526316,
       17.89473684, 18.68421053, 19.47368421, 20.26315789, 21.05263158,
       21.84210526, 22.63157895, 23.42105263, 24.21052632, 25.        ])

## Numpy Operations

In [51]:
arr2 * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
arr2 % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [54]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# 1. Convert [ (1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12) ] in a 2d array of 3, 4
# 2. Create a 2D array of 20 elements.
# 3. Create an array from 10, 50 with a step of 5 and convert to 3 possible array shape combinations.

In [59]:
np.arange(10, 18).reshape(2, 2, 2)

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

In [5]:
mat3 = np.arange(5, 50, 5).reshape((3, 3))

In [8]:
bool_arr = mat3 % 10 == 0

In [9]:
mat3[ bool_arr ]

array([10, 20, 30, 40])

In [12]:
mat3 *2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
mat4= np.arange(1, 10).reshape((3, 3))

In [15]:
mat4 + mat3

array([[ 6, 12, 18],
       [24, 30, 36],
       [42, 48, 54]])

In [16]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
mat3 * mat4

array([[  5,  20,  45],
       [ 80, 125, 180],
       [245, 320, 405]])

In [18]:
# matrix multiplication
mat3 @ mat4

array([[150, 180, 210],
       [330, 405, 480],
       [510, 630, 750]])

In [20]:
mat3.max()

45

In [21]:
mat3.min()

5

In [22]:
mat3.sum()

225

In [23]:
mat3.mean()

25.0

In [25]:
np.random.random((4, 4))

array([[0.94061847, 0.61470642, 0.82544079, 0.98584082],
       [0.29912621, 0.94853157, 0.33837523, 0.5117276 ],
       [0.97541455, 0.75101312, 0.02255021, 0.37238076],
       [0.02607219, 0.96368257, 0.5188039 , 0.2734513 ]])

In [28]:
np.random.randint( 10, 20, (4, 4))

array([[12, 10, 17, 18],
       [13, 11, 14, 14],
       [17, 17, 15, 12],
       [16, 10, 11, 16]])

In [29]:
import random

In [34]:
random.randint(1, 6)

2

In [37]:
random.random()

0.6288494741051017

In [42]:
random.choice([ 'gta', 'resident evil 4', 'wot', 'super mario' ])

'gta'

In [49]:
random.choices([ 'gta', 'resident evil 4', 'wot', 'super mario' ], k=2)

['wot', 'wot']

In [63]:
ultimatrix = np.arange(25).reshape((5, 5))

In [64]:
ultimatrix[1][2]

7

In [65]:
ultimatrix[0]

array([0, 1, 2, 3, 4])

In [58]:
ultimatrix[1, 1]

6

In [61]:
ultimatrix[ 1, 1:4 ]

array([6, 7, 8])

In [62]:
ultimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
ultimatrix[2:5, 2]

array([12, 17, 22])

In [69]:
ultimatrix[2:5, 2]

array([12, 17, 22])

In [70]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.vstack( (mat3 , mat4) )

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [74]:
mat5 = np.arange(1, 7).reshape((2, 3))

In [75]:
mat5

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.vstack((mat4, mat5))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.hstack( (mat3, mat4) )

array([[ 5, 10, 15,  1,  2,  3],
       [20, 25, 30,  4,  5,  6],
       [35, 40, 45,  7,  8,  9]])

In [79]:
np.hstack( (mat4, mat5) )

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [80]:
mat6 = np.arange(1, 7).reshape((3, 2))

In [83]:
np.hstack( (mat3, mat6) )

array([[ 5, 10, 15,  1,  2],
       [20, 25, 30,  3,  4],
       [35, 40, 45,  5,  6]])